apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shipyard

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - server.deployment.yaml
  - server.service.yaml
  - worker.deployment.yaml
  - web.deployment.yaml
  - web.service.yaml
  - ingress.yaml

